Progress...

diff --git a/scythe-server b/scythe-server
--- a/scythe-server
+++ b/scythe-server
@@ -2,9 +2,9 @@
 
 SCYTHE_SERVER_VERSION=0.6.0
 
-export TEACHER_ID="$1" # this is safe since it is in .ssh/authorized_keys
-if [ -z "$TEACHER_ID" ]; then
-    echo "scythe-server: missing TEACHER_ID" >&2
+export TESTER_ID="$1" # this is safe since it is in .ssh/authorized_keys
+if [ -z "$TESTER_ID" ]; then
+    echo "scythe-server: missing TESTER_ID" >&2
     exit 1
 fi
 
@@ -18,16 +18,17 @@ fi
 
 export SCYTHE_COMMAND="${arguments[1]}"
 
-export EXAM_ID="${arguments[2]}"
-if [ -z "$EXAM_ID" ]; then
-    echo "scythe-server: missing EXAM_ID" >&2
+export SESSION_ID="${arguments[2]}"
+if [ -z "$SESSION_ID" ]; then
+    echo "scythe-server: missing SESSION_ID" >&2
     exit 1
 fi
 
-export SCYTHE_ROOT="$HOME/scythe-root/$TEACHER_ID/$EXAM_ID"
+export SCYTHE_ROOT="$HOME/scythe-root/$TESTER_ID/$SESSION_ID"
 export SCYTHE_CONF="$SCYTHE_ROOT/conf.py"
 export SCYTHE_UPLOADS="$SCYTHE_ROOT/uploads"
-export SCYTHE_NAME="${TEACHER_ID}-${EXAM_ID}"
+export SCYTHE_NAME="${TESTER_ID}-${SESSION_ID}"
+export SCYTHE_SESSION="scythe=session-${SCYTHE_NAME}"
 
 mkdir -p "$SCYTHE_ROOT"
 mkdir -p "$SCYTHE_UPLOADS"
@@ -35,11 +36,11 @@ if [ ! -r "$SCYTHE_UPLOADS/no.log" ]; then
     touch "$SCYTHE_UPLOADS/no.log" # to avoid tail failures
 fi
 
-echo -e "$(date)\t$SSH_CONNECTION\t$TEACHER_ID\t$SCYTHE_COMMAND\t$SCYTHE_CONF" >> "$HOME/scythe-server.log"
+echo -e "$(date)\t$SSH_CONNECTION\t$TESTER_ID\t$SCYTHE_COMMAND\t$SESSION_ID" >> "$HOME/scythe-server.log"
 
 check_conf() {
     if [ ! -r "$SCYTHE_CONF" ]; then
-        echo "scythe-server: missing configuation '$SCYTHE_CONF' for teacher '$TEACHER_ID'" >&2
+        echo "scythe-server: missing configuation '$SCYTHE_CONF' for tester '$TESTER_ID'" >&2
         exit 1
     fi
 }
@@ -47,36 +48,40 @@ check_conf() {
 case "$SCYTHE_COMMAND" in
     push)
         if [ -r "$SCYTHE_ROOT/conf.py" ]; then
-            echo "scythe-server push: replacing '$EXAM_ID' configuration for teacher '$TEACHER_ID'" >&2
+            echo "scythe-server: push: replacing '$SESSION_ID' configuration for tester '$TESTER_ID'" >&2
         else
-            echo "scythe-server push: installing '$EXAM_ID' configuration for teacher '$TEACHER_ID'" >&2
+            echo "scythe-server: push: installing '$SESSION_ID' configuration for tester '$TESTER_ID'" >&2
         fi
         cat > "$SCYTHE_ROOT/conf.py"
     ;;
     start)
         check_conf
-        echo "scythe-server start: removing signature for test UID '000000' in '$EXAM_ID' for teacher '$TEACHER_ID'" >&2
+        echo "scythe-server: start: removing signature for test UID '000000' in '$SESSION_ID' for tester '$TESTER_ID'" >&2
         rm -f "$SCYTHE_UPLOADS/000000/SIGNATURE.tsv"
-        echo "scythe-server start: about to start '$EXAM_ID' for teacher '$TEACHER_ID'" >&2
-        if docker ps -a --filter label=scythe=tmserver | grep -q "$SCYTHE_NAME"; then
-            echo "scythe-server sart: killing old instance..." $(docker rm -f "$SCYTHE_NAME") >&2
+        echo "scythe-server: start: about to start '$SESSION_ID' for tester '$TESTER_ID'" >&2
+        dids=$(docker ps -a --filter label="$SCYTHE_SESSION" --format '{{.ID}}')
+        if [ ! -z "$dids"]; then
+            echo "scythe-server: sart: killing old instances..." $(docker rm -f $dids) >&2
         fi
-        did=$(docker run --user "$(id -u):$(id -g)" -l scythe=tmserver --name "$SCYTHE_NAME" -d --network=scythe -v "$SCYTHE_UPLOADS":/uploads -v "$SCYTHE_CONF":/app/conf.py:ro scythe/tmserver)
-        echo "scythe-server start: started container '$SCYTHE_NAME' with conf '$SCYTHE_CONF', and uploads in '$SCYTHE_UPLOADS' (docker id '$did')..." >&2
+        did=$(docker run --user "$(id -u):$(id -g)" -l "$SCYTHE_SESSION" --name "${SCYTHE_NAME}-tm" -d --network=scythe -v "$SCYTHE_UPLOADS":/uploads -v "$SCYTHE_CONF":/app/conf.py:ro scythe/tmserver)
+        echo "scythe-server: start: started tmserver '${SCYTHE_NAME}-tm' with conf '$SCYTHE_CONF', and uploads in '$SCYTHE_UPLOADS' (docker id '$did')..." >&2
+        did=$(docker run -l "$SCYTHE_SESSION" --name "{$SCYTHE_NAME}-st" -d --network=scythe -e SCYTHE_SESSION_ID="$SESSION_ID" -v "$SCYTHE_UPLOADS":/uploads:ro scythe/ststager -s "$SESSION_ID")
+        echo "scythe-server: start: started ststager '${SCYTHE_NAME}-st' with uploads in '$SCYTHE_UPLOADS' (docker id '$did')..." >&2
     ;;
     stop)
         check_conf
-        echo "scythe-server stop: stopping '$EXAM_ID' for teacher '$TEACHER_ID'" >&2
-        if docker ps -a --filter label=scythe=tmserver | grep -q "$SCYTHE_NAME"; then
-            echo "scythe-server stop: killing old instance..." $(docker rm -f "$SCYTHE_NAME") >&2
+        echo "scythe-server: stop: stopping '$SESSION_ID' containers for tester '$TESTER_ID'" >&2
+        dids=$(docker ps -a --filter label="$SCYTHE_SESSION" --format '{{.ID}}')
+        if [ ! -z "$dids"]; then
+            echo "scythe-server: stop: killing old session instances..." $(docker rm -f $dids) >&2
         else
-            echo "scythe-server stop: no running container found" >&2
+            echo "scythe-server: stop: no running container found" >&2
         fi
     ;;
     status)
         check_conf
-        echo "scythe-server status: running sessions for teacher '$TEACHER_ID'" >&2
-        docker ps --filter label=scythe=tmserver | grep "${TEACHER_ID}"
+        echo "scythe-server: status: running sessions for tester '$TESTER_ID'" >&2
+        docker ps --filter label="$SCYTHE_SESSION" --format "table {{.ID}}\t{{.Names}}\t{{.Labels}}"
     ;;
     get)
         check_conf
@@ -84,11 +89,11 @@ case "$SCYTHE_COMMAND" in
     ;;
     logtail)
         check_conf
-        echo "scythe-server logtail: tailing '$EXAM_ID' logs for teacher '$TEACHER_ID', hit ctrl-c to stop..." >&2
+        echo "scythe-server: logtail: tailing '$SESSION_ID' logs for tester '$TESTER_ID', hit ctrl-c to stop..." >&2
         tail -f "$SCYTHE_ROOT/uploads"/*.log
     ;;
     version)
-        echo "scythe-server version: version v$SCYTHE_SERVER_VERSION" >&2
+        echo "scythe-server: version: version v$SCYTHE_SERVER_VERSION" >&2
         exit 0
     ;;
     *)
